# Generated by Django 5.2.16 on 2026-08-01 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.PositiveSmallIntegerField()),
                ('monthly_income', models.PositiveIntegerField()),
                ('current_cash', models.PositiveIntegerField()),
                ('monthly_living_cost', models.PositiveIntegerField()),
                ('debt_balance', models.PositiveIntegerField(default=0)),
                ('debt_monthly_payment', models.PositiveIntegerField(default=0)),
                ('target_asset', models.PositiveIntegerField()),
                ('target_months', models.PositiveSmallIntegerField(default=36)),
                ('current_monthly_housing_cost', models.PositiveIntegerField(default=0)),
                ('current_housing_type', models.CharField(choices=[('family', '가족과 거주'), ('monthly_rent', '월세'), ('jeonse', '전세')], default='family', max_length=20)),
                ('is_target_asset_default', models.BooleanField(default=False)),
                ('is_target_months_default', models.BooleanField(default=False)),
                ('is_living_cost_default', models.BooleanField(default=False)),
                ('existing_loan_interest_rate', models.FloatField(default=0.0)),
                ('existing_loan_remaining_months', models.PositiveSmallIntegerField(default=0)),
                ('existing_loan_repayment_type', models.CharField(choices=[('amortizing', '원리금균등'), ('interest_only', '이자만 상환'), ('none', '대출 없음')], default='none', max_length=20)),
                ('event_answers', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
