# Generated by Django 5.2.16 on 2026-08-01 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='event_answers',
            field=models.JSONField(default=list),
        ),
    ]
