# Generated by Django 5.2.16 on 2026-08-01 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_profile_event_answers'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='existing_loan_interest_rate',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='profile',
            name='existing_loan_remaining_months',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='existing_loan_repayment_type',
            field=models.CharField(choices=[('amortizing', '원리금균등'), ('interest_only', '이자만 상환'), ('none', '대출 없음')], default='none', max_length=20),
        ),
    ]
