# Generated by Django 5.2.16 on 2026-08-01 12:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scenario_type', models.CharField(choices=[('move_now', '지금 독립'), ('wait_12m', '12개월 대기'), ('lower_cost_region', '저비용 지역'), ('high_deposit', '고보증금')], default='move_now', max_length=20)),
                ('district', models.CharField(choices=[('강남구', '강남구'), ('강동구', '강동구'), ('강북구', '강북구'), ('강서구', '강서구'), ('관악구', '관악구'), ('광진구', '광진구'), ('구로구', '구로구'), ('금천구', '금천구'), ('노원구', '노원구'), ('도봉구', '도봉구'), ('동대문구', '동대문구'), ('동작구', '동작구'), ('마포구', '마포구'), ('서대문구', '서대문구'), ('서초구', '서초구'), ('성동구', '성동구'), ('성북구', '성북구'), ('송파구', '송파구'), ('양천구', '양천구'), ('영등포구', '영등포구'), ('용산구', '용산구'), ('은평구', '은평구'), ('종로구', '종로구'), ('중구', '중구'), ('중랑구', '중랑구')], max_length=10)),
                ('housing_type', models.CharField(choices=[('아파트', '아파트'), ('오피스텔', '오피스텔'), ('연립·다세대', '연립·다세대')], max_length=10)),
                ('desired_area_m2', models.FloatField(default=35.0)),
                ('move_in_after_months', models.PositiveSmallIntegerField(default=0)),
                ('deposit', models.PositiveIntegerField()),
                ('monthly_rent', models.PositiveIntegerField(default=0)),
                ('contract_months', models.PositiveSmallIntegerField(default=24)),
                ('deposit_loan_amount', models.PositiveIntegerField(default=0)),
                ('loan_interest_rate', models.FloatField(default=0.0)),
                ('loan_repayment_type', models.CharField(choices=[('interest_only', '이자만 상환'), ('none', '대출 없음')], default='none', max_length=20)),
                ('moving_cost', models.PositiveIntegerField(default=0)),
                ('brokerage_fee', models.PositiveIntegerField(default=0)),
                ('monthly_support', models.PositiveIntegerField(default=0)),
                ('support_months', models.PositiveSmallIntegerField(default=0)),
                ('deposit_return_rate', models.FloatField(default=0.98)),
                ('contract_type', models.CharField(choices=[('monthly_rent', '월세'), ('jeonse', '전세')], default='monthly_rent', max_length=20)),
                ('conversion_rate_annual', models.FloatField(default=0.05)),
                ('contract_slider_pct', models.SmallIntegerField(default=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scenarios', to='profiles.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scenario_id_ai', models.CharField(blank=True, default='', max_length=50)),
                ('achievement_score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('suitability', models.CharField(blank=True, default='', max_length=10)),
                ('goal_probability', models.FloatField()),
                ('district', models.CharField(max_length=10)),
                ('housing_type', models.CharField(max_length=10)),
                ('raw_payload', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.profile')),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simulation.scenario')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TimingComparison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_payload', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('base_scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simulation.scenario')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.profile')),
            ],
        ),
    ]
