# Generated by Django 5.2.16 on 2026-08-01 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulation', '0002_timingcomparison'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diagnosis',
            old_name='goal_prob',
            new_name='goal_probability',
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='achievement_score',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='scenario_id_ai',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='suitability',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='scenario',
            name='desired_area_m2',
            field=models.FloatField(default=35.0),
        ),
        migrations.AlterField(
            model_name='scenario',
            name='housing_type',
            field=models.CharField(choices=[('아파트', '아파트'), ('오피스텔', '오피스텔'), ('연립·다세대', '연립·다세대')], max_length=10),
        ),
    ]
