# Generated by Django 5.2.16 on 2026-08-01 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SupportProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age_min', models.PositiveSmallIntegerField()),
                ('age_max', models.PositiveSmallIntegerField()),
                ('income_ratio_min', models.FloatField(blank=True, null=True)),
                ('income_ratio_max', models.FloatField(blank=True, null=True)),
                ('income_max_annual', models.PositiveIntegerField(blank=True, null=True)),
                ('asset_max', models.PositiveIntegerField(blank=True, null=True)),
                ('deposit_max', models.PositiveIntegerField(blank=True, null=True)),
                ('rent_max', models.PositiveIntegerField(blank=True, null=True)),
                ('benefit_desc', models.CharField(max_length=200)),
                ('source_url', models.URLField()),
                ('is_kb_exclusive', models.BooleanField(default=False)),
                ('is_kb_available', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-is_kb_exclusive', 'name'],
            },
        ),
    ]
